routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Client\ImagesController::class, 'index'])
    ->name('images.index');

Route::resource('users', \App\Http\Controllers\Client\UsersController::class)
    ->only('show', 'edit', 'update')
    ->middleware('auth');

Route::resource('images', \App\Http\Controllers\Client\ImagesController::class)
    ->except('index', 'create', 'store');

Route::get('imagas/create', [\App\Http\Controllers\Client\ImagesController::class, 'create'])
    ->name('images.create')->middleware('auth');

Route::post('images', [\App\Http\Controllers\Client\ImagesController::class, 'store'])
    ->name('images.store')->middleware('auth');

Route::resource('comments', \App\Http\Controllers\Client\CommentsController::class)
    ->only('store', 'destroy')
    ->middleware('auth');


Route::prefix('admin')->middleware(['auth', 'admin'])->name('admin.')->group(function () {
    Route::resources([
        'images' => \App\Http\Controllers\Admin\ImagesController::class,
        'comments' => \App\Http\Controllers\Admin\CommentsController::class,
        'users' => \App\Http\Controllers\Admin\UsersController::class
    ]);
});

Auth::routes();

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'img',
        'user_id',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderBy('id', 'desc');
    }
}

app/Http/Controllers/Admin/ImagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Image;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $images = Image::orderBy('id', 'desc')->paginate(6);
        return view('admin.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $users = User::all();
        return view('admin.images.create', compact( 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $image = new Image();

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $image->user_id = $request->get('user_id');
        $image->name = $request->get('name');
        if ($request->hasFile('img')) {
            $image->img = $request->file('img')->store('img', 'public');
        }
        $image->save();

        return redirect()->route('admin.images.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Image $image
     * @return Application|Factory|View
     */
    public function show(Image $image)
    {
        $comments = $image->comments;
        if ($comments->count() > 0) {
            $avg = round($comments->sum('rating') / $comments->count(), 1);
        } else {
            $avg = 0;
        }
        return view('admin.images.show', compact('image', 'avg', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(Image $image)
    {
        return view('admin.images.edit', compact('image'));
    }

    /**
     * @param Request $request
     * @param Image $image
     * @return RedirectResponse
     */
    public function update(Request $request, Image $image): RedirectResponse
    {
        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $old_img_path = null;
        $data = $request->all();
        if ($request->hasFile('img')) {
            $path = $request->file('img')->store('img', 'public');
            $data['img'] = $path;

            $old_img_path = $image->img;
        }
        if($old_img_path) {
            Storage::delete("public/" . $old_img_path);
        }

        $image->update($data);

        return redirect()->route('admin.images.show', ['image' => $image]);
    }

    /**
     * @param Image $image
     * @return RedirectResponse
     */
    public function destroy(Image $image): RedirectResponse
    {
        if($image->img) {
            Storage::delete("public/" . $image->img);
        }
        $image->delete();

        return redirect()->route('admin.images.index');
    }
}

app/Http/Controllers/Client/CommentsController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CommentsController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'body' => 'bail|required|max:292|min:2|string',
            'rating' => 'bail|required|digits_between:1,5',
            'user_id' => 'required',
            'image_id' => 'required',
        ]);

        $comment = new Comment();
        $comment->body = $request->get('body');
        $comment->rating = $request->get('rating');
        $comment->user_id = $request->get('user_id');
        $comment->image_id = $request->get('image_id');

        $comment->save();

        return redirect()->route('images.show', ['image' => $comment->image]);
    }

    /**
     * @param Comment $comment
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Comment $comment): RedirectResponse
    {
        $this->authorize('delete', $comment);
        $comment->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Client/ImagesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $images = Image::orderBy('id', 'desc')->paginate(6);

        return view('client.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('client.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $image = new Image();

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $image->user_id = $request->get('user_id');
        $image->name = $request->get('name');
        if ($request->hasFile('img')) {
            $image->img = $request->file('img')->store('img', 'public');
        }
        $image->save();

        return redirect()->route('images.index');
    }


    /**
     * @param Image $image
     * @return Application|Factory|View
     */
    public function show(Image $image)
    {
        $comments = $image->comments;
        if ($comments->count() > 0) {
            $avg = round($comments->sum('rating') / $comments->count(), 1);
        } else {
            $avg = 0;
        }
        return view('client.images.show', compact('image', 'avg', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(Image $image)
    {
        return view('client.images.edit', compact('image'));
    }


    /**
     * @param Request $request
     * @param Image $image
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(Request $request, Image $image): RedirectResponse
    {
        $this->authorize('update', $image);

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $old_img_path = null;
        $data = $request->all();
        if ($request->hasFile('img')) {
            $path = $request->file('img')->store('img', 'public');
            $data['img'] = $path;

            $old_img_path = $image->img;
        }
        if($old_img_path) {
            Storage::delete("public/" . $old_img_path);
        }

        $image->update($data);

        return redirect()->route('images.show', ['image' => $image]);
    }


    /**
     * @param Image $image
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Image $image): RedirectResponse
    {
        $this->authorize('delete', $image);

        if($image->img) {
            Storage::delete("public/" . $image->img);
        }
        $image->delete();

        return redirect()->route('images.index');
    }
}

app/Http/Controllers/Client/UsersController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }


    /**
     * @param User $user
     * @return Application|Factory|View
     */
    public function show(User $user)
    {
        return view('client.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(User $user)
    {
        return view('client.users.edit', compact('user'));
    }


    /**
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $request->validate(['name' => ['required', 'string', 'max:255']]);
        $user->name = $request->get('name');
        $user->save();

        return redirect()->route('users.show', ['user' => $user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/client/images/create.blade.php
@extends('layouts.app')

@section('content')
    <h3><b>Adding new Image</b></h3>

    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('images.store')}}">
        @csrf
        <div class="col-md-6">
            <label for="name"><b>Image name</b></label>
            <input type="text" value="{{ old('name') }}"
                   class="form-control  {{ $errors->has('name') == true ? 'is-invalid' : null }} "
                   id="name" name="name" placeholder="Image Name">
            @error('name')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div>
                <label for="formFile" class="form-label mt-3"><b>Image</b></label>
                <input class="form-control {{ $errors->has('img') == true ? 'is-invalid' : null }} "
                       type="file" id="formFile" name="img">
                @error('img')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="hidden" name="user_id" value="{{Auth::id()}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Add</button>
                <a href=" {{ route('images.index') }} " class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>

@endsection

resources/views/client/images/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3><b>Editing new Image</b></h3>

    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('images.update', ['image' => $image])}}">
        @csrf
        @method('PUT')
        <div class="col-md-6">
            <label for="name"><b>Image name</b></label>
            <input type="text" value="{{ old('name') }}"
                   class="form-control  {{ $errors->has('name') == true ? 'is-invalid' : null }} "
                   id="name" name="name" placeholder="Image Name">
            @error('name')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div class="my-3">
                <img src="{{asset('/storage/' . $image->img)}}" alt="{{$image->img}}" style="width:50px;height:50px;">
                <input class="form-control {{ $errors->has('img') == true ? 'is-invalid' : null }} "
                       type="file" id="formFile" name="img" value="{{$image->img}}">
                @error('img')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="hidden" name="user_id" value="{{Auth::id()}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Add</button>
                <a href=" {{ route('images.index') }} " class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>

@endsection

resources/views/client/images/index.blade.php
@extends('layouts.app')
@section('content')

    <a href="{{ route('images.create') }}" class="btn btn-outline-success mb-4">Add New Image</a>
    <div class="row row-cols-1 row-cols-md-3">
        @foreach($images as $image)
            <div class="col mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="{{route('images.show', ['image' => $image])}}">
                            <img src="{{asset('/storage/' . $image->img)}}" alt="{{$image->img}}" class="card-img-top mb-2">
                        </a>
                        <h5 class="card-title">{{$image->name}}</h5>
                        <small class="text-muted">By:
                            <a href="{{route('users.show', ['user' => $image->user])}}" class="text-decoration-none">{{$image->user->name}}</a>
                        </small>
                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            {{ $images->links('pagination::bootstrap-4') }}
        </div>
    </div>

@endsection

resources/views/client/images/show.blade.php
@extends('layouts.app')

@section('content')
    @can('update', $image)
        <form class="my-3" action="{{ route('images.destroy', ['image' => $image]) }}"
              method="POST">
            @method('DELETE')
            @csrf
            <button type="submit" class="btn btn-outline-danger btn-sm">Delete Image</button>
            <a href="{{route('images.edit', ['image' => $image])}}" class="btn btn-outline-info btn-sm">Edit Image</a>
        </form>
    @endcan

    <h3><b>{{$image->name}}</b></h3>
        <div>
            <img src="{{asset('/storage/' . $image->img)}}" class="img-fluid my-3"
                 style=" max-width: 100%;" alt="{{$image->img}}">
        </div>
        <div>
            <span>
                <b>Average score: </b>
                {{$avg}}
            </span>
        </div>

    <h3 class="mt-4"><b>Add Comment</b></h3>
    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('comments.store')}}">
        @csrf
        <div class="col-md-6">
            <label for="body"><b>Comment</b></label>

            <textarea name="body" class="form-control {{ $errors->has('body') == true ? 'is-invalid' : null }} "
                      placeholder="Leave a comment here" id="body"
                      style="height: 100px">{{ old('body') }}</textarea>
            @error('body')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div class="form-group col-md-4">
                <label for="rating">Score</label>
                <select id="rating" class="form-control {{ $errors->has('rating') == true ? 'is-invalid' : null }} "
                        name="rating">
                    <option selected>Choose...</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                @error('rating')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="hidden" name="user_id" value="{{Auth::id()}}">
            <input type="hidden" name="image_id" value="{{$image->id}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Add Comment</button>
            </div>
        </div>
    </form>

    <div class="list-group mt-3">
        @foreach($comments as $comment)
        <div  class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><b>By:</b> {{$comment->user->name}}, <b class="text-success">Score: {{$comment->rating}}</b></h5>
                @can('delete', $comment)
                    <form class="my-3" action="{{ route('comments.destroy', ['comment' => $comment]) }}"
                          method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete Comment</button>
                    </form>
                @endcan
            </div>
            <p class="mb-1">{{$comment->body}}</p>
        </div>
        @endforeach
    </div>
@endsection