routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Client\ImagesController::class, 'index'])
    ->name('images.index');

Route::resource('users', \App\Http\Controllers\Client\UsersController::class)
    ->only('show', 'edit', 'update')
    ->middleware('auth');

Route::resource('images', \App\Http\Controllers\Client\ImagesController::class)
    ->except('index', 'create', 'store');

Route::get('imagas/create', [\App\Http\Controllers\Client\ImagesController::class, 'create'])
    ->name('images.create')->middleware('auth');

Route::post('images', [\App\Http\Controllers\Client\ImagesController::class, 'store'])
    ->name('images.store')->middleware('auth');

Route::resource('comments', \App\Http\Controllers\Client\CommentsController::class)
    ->only('store', 'destroy')
    ->middleware('auth');


Route::prefix('admin')->middleware(['auth', 'admin'])->name('admin.')->group(function () {
    Route::resources([
        'images' => \App\Http\Controllers\Admin\ImagesController::class,
        'comments' => \App\Http\Controllers\Admin\CommentsController::class,
        'users' => \App\Http\Controllers\Admin\UsersController::class
    ]);
});

Auth::routes();

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'img',
        'user_id',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderBy('id', 'desc');
    }
}

app/Http/Controllers/Admin/ImagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Image;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $images = Image::orderBy('id', 'desc')->paginate(6);
        return view('admin.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $users = User::all();
        return view('admin.images.create', compact( 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $image = new Image();

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $image->user_id = $request->get('user_id');
        $image->name = $request->get('name');
        if ($request->hasFile('img')) {
            $image->img = $request->file('img')->store('img', 'public');
        }
        $image->save();

        return redirect()->route('admin.images.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Image $image
     * @return Application|Factory|View
     */
    public function show(Image $image)
    {
        $comments = $image->comments;
        if ($comments->count() > 0) {
            $avg = round($comments->sum('rating') / $comments->count(), 1);
        } else {
            $avg = 0;
        }
        return view('admin.images.show', compact('image', 'avg', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(Image $image)
    {
        return view('admin.images.edit', compact('image'));
    }

    /**
     * @param Request $request
     * @param Image $image
     * @return RedirectResponse
     */
    public function update(Request $request, Image $image): RedirectResponse
    {
        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $old_img_path = null;
        $data = $request->all();
        if ($request->hasFile('img')) {
            $path = $request->file('img')->store('img', 'public');
            $data['img'] = $path;

            $old_img_path = $image->img;
        }
        if($old_img_path) {
            Storage::delete("public/" . $old_img_path);
        }

        $image->update($data);

        return redirect()->route('admin.images.show', ['image' => $image]);
    }

    /**
     * @param Image $image
     * @return RedirectResponse
     */
    public function destroy(Image $image): RedirectResponse
    {
        if($image->img) {
            Storage::delete("public/" . $image->img);
        }
        $image->delete();

        return redirect()->route('admin.images.index');
    }
}

app/Http/Controllers/Client/ImagesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $images = Image::orderBy('id', 'desc')->paginate(6);

        return view('client.images.index', compact('images'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('client.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $image = new Image();

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $image->user_id = $request->get('user_id');
        $image->name = $request->get('name');
        if ($request->hasFile('img')) {
            $image->img = $request->file('img')->store('img', 'public');
        }
        $image->save();

        return redirect()->route('images.index');
    }


    /**
     * @param Image $image
     * @return Application|Factory|View
     */
    public function show(Image $image)
    {
        $comments = $image->comments;
        if ($comments->count() > 0) {
            $avg = round($comments->sum('rating') / $comments->count(), 1);
        } else {
            $avg = 0;
        }
        return view('client.images.show', compact('image', 'avg', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(Image $image)
    {
        return view('client.images.edit', compact('image'));
    }


    /**
     * @param Request $request
     * @param Image $image
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(Request $request, Image $image): RedirectResponse
    {
        $this->authorize('update', $image);

        $request->validate([
            'user_id' => ['required'],
            'img' => ['required', 'mimes:jpg,png'],
            'name' => ['required', 'max:192', 'min:2', 'string'],
        ]);

        $old_img_path = null;
        $data = $request->all();
        if ($request->hasFile('img')) {
            $path = $request->file('img')->store('img', 'public');
            $data['img'] = $path;

            $old_img_path = $image->img;
        }
        if($old_img_path) {
            Storage::delete("public/" . $old_img_path);
        }

        $image->update($data);

        return redirect()->route('images.show', ['image' => $image]);
    }


    /**
     * @param Image $image
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Image $image): RedirectResponse
    {
        $this->authorize('delete', $image);

        if($image->img) {
            Storage::delete("public/" . $image->img);
        }
        $image->delete();

        return redirect()->route('images.index');
    }
}

resources/views/admin/images/create.blade.php
@extends('layouts.app')

@section('content')
    <h3><b>Adding new Image</b></h3>

    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('admin.images.store')}}">
        @csrf
        <div class="col-md-6">
            <label for="name"><b>Image name</b></label>
            <input type="text" value="{{ old('name') }}"
                   class="form-control  {{ $errors->has('name') == true ? 'is-invalid' : null }} "
                   id="name" name="name" placeholder="Image Name">
            @error('name')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div>
                <label for="formFile" class="form-label mt-3"><b>Image</b></label>
                <input class="form-control {{ $errors->has('img') == true ? 'is-invalid' : null }} "
                       type="file" id="formFile" name="img">
                @error('img')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <div>
                <label for="user_id"><b>User</b></label>
                <select id="user_id" class="form-control {{ $errors->has('user_id') == true ? 'is-invalid' : null }} "
                        name="user_id">
                    <option selected>Choose...</option>
                    @foreach($users as $user)
                        <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                </select>
                @error('rating')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="mt-3">
                <button type="submit" class="btn btn-secondary">Add</button>
                <a href=" {{ route('images.index') }} " class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/images/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3><b>Editing new Image</b></h3>

    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('admin.images.update', ['image' => $image])}}">
        @csrf
        @method('PUT')
        <div class="col-md-6">
            <label for="name"><b>Image name</b></label>
            <input type="text" value="{{ $image->name }}"
                   class="form-control  {{ $errors->has('name') == true ? 'is-invalid' : null }} "
                   id="name" name="name" placeholder="Image Name">
            @error('name')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div class="my-3">
                <img src="{{asset('/storage/' . $image->img)}}" alt="{{$image->img}}" style="width:50px;height:50px;">
                <input class="form-control {{ $errors->has('img') == true ? 'is-invalid' : null }} "
                       type="file" id="formFile" name="img" value="{{$image->img}}">
                @error('img')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="hidden" name="user_id" value="{{$image->user->id}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Add</button>
                <a href=" {{ route('admin.images.index') }} " class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/images/index.blade.php
@extends('layouts.app')
@section('content')

    <a href="{{route('admin.images.create')}}" class="btn btn-outline-success">Create Image</a>
    <table class="table mt-3" style="padding-top: 30px">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Image</th>
            <th scope="col" class="text-center">Name</th>
            <th scope="col" class="text-center">User Name</th>
            <th scope="col" class="text-right">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($images as $image)
            <tr>
                <td>
                    <a href="{{route('admin.images.show', ['image' => $image])}}" class="text-decoration-none text-dark">
                        <img src="{{asset('/storage/' . $image->img)}}" alt="{{asset('/storage/' . $image->img)}}"
                         width="70px" height="70px">
                    </a>
                </td>
                <td class="text-center">
                    <a href="{{route('admin.images.show', ['image' => $image])}}" class="text-decoration-none text-dark">
                        {{$image->name}}
                    </a>
                </td>

                <td class="text-center">
                    <a href="{{route('admin.users.show', ['user' => $image->user])}}" class="text-decoration-none text-dark">
                        {{$image->user->name}}
                    </a>
                </td>

                <td class="text-right">
                    <div class="btn-group">
                        <form class="my-3" action="{{ route('admin.images.destroy', ['image' => $image]) }}"
                              method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete Image</button>
                            <a href="{{route('admin.images.edit', ['image' => $image])}}"
                               class="btn btn-outline-info btn-sm">Edit Image</a>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            {{ $images->links('pagination::bootstrap-4') }}
        </div>
    </div>

@endsection

resources/views/admin/images/show.blade.php
@extends('layouts.app')

@section('content')
    <form class="my-3" action="{{ route('admin.images.destroy', ['image' => $image]) }}"
          method="POST">
        @method('DELETE')
        @csrf
        <button type="submit" class="btn btn-outline-danger btn-sm">Delete Image</button>
    </form>

    <h3><b>{{$image->name}}</b></h3>
    <div>
        <img src="{{asset('/storage/' . $image->img)}}" class="img-fluid my-3"
             style=" max-width: 100%;" alt="{{$image->img}}">
    </div>
    <div>
        <span>
        <b>Average score: </b>
            {{$avg}}
        </span>
    </div>

    <h3 class="mt-4"><b>Add Comment</b></h3>
    <form enctype="multipart/form-data" class=" row g-3" method="POST" action="{{route('admin.comments.store')}}">
        @csrf
        <div class="col-md-6">
            <label for="body"><b>Comment</b></label>

            <textarea name="body" class="form-control {{ $errors->has('body') == true ? 'is-invalid' : null }} "
                      placeholder="Leave a comment here" id="body"
                      style="height: 100px">{{ old('body') }}</textarea>
            @error('body')
            <div class="text-danger"> {{ $message }} </div>
            @enderror

            <div class="form-group col-md-4">
                <label for="rating">Score</label>
                <select id="rating" class="form-control {{ $errors->has('rating') == true ? 'is-invalid' : null }} "
                        name="rating">
                    <option selected>Choose...</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                @error('rating')
                <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="hidden" name="user_id" value="{{Auth::id()}}">
            <input type="hidden" name="image_id" value="{{$image->id}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Add Comment</button>
            </div>
        </div>
    </form>

    <div class="list-group mt-3">
        @foreach($comments as $comment)
            <div  class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><b>By:</b> {{$comment->user->name}}, <b class="text-success">Score: {{$comment->rating}}</b></h5>
                    <form class="my-3" action="{{ route('admin.comments.destroy', ['comment' => $comment]) }}"
                          method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete Comment</button>
                    </form>
                </div>
                <p class="mb-1">{{$comment->body}}</p>
            </div>
        @endforeach
    </div>
@endsection