routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Client\ImagesController::class, 'index'])
    ->name('images.index');

Route::resource('users', \App\Http\Controllers\Client\UsersController::class)
    ->only('show', 'edit', 'update')
    ->middleware('auth');

Route::resource('images', \App\Http\Controllers\Client\ImagesController::class)
    ->except('index', 'create', 'store');

Route::get('imagas/create', [\App\Http\Controllers\Client\ImagesController::class, 'create'])
    ->name('images.create')->middleware('auth');

Route::post('images', [\App\Http\Controllers\Client\ImagesController::class, 'store'])
    ->name('images.store')->middleware('auth');

Route::resource('comments', \App\Http\Controllers\Client\CommentsController::class)
    ->only('store', 'destroy')
    ->middleware('auth');


Route::prefix('admin')->middleware(['auth', 'admin'])->name('admin.')->group(function () {
    Route::resources([
        'images' => \App\Http\Controllers\Admin\ImagesController::class,
        'comments' => \App\Http\Controllers\Admin\CommentsController::class,
        'users' => \App\Http\Controllers\Admin\UsersController::class
    ]);
});

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return HasMany
     */
    public function images(): HasMany
    {
        return $this->hasMany(Image::class)->orderBy('id', 'desc');
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderBy('id', 'desc');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->paginate(6);
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $user = new User();
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->password = $request->get('password');
        $user->save();

        return redirect()->route('admin.users.index');
    }


    /**
     * @param User $user
     * @return Application|Factory|View
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Application|Factory|View
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
        ]);

        $data = $request->all();
        $user->update($data);

        return redirect()->route('admin.users.index');
    }


    /**
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();
        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/Client/UsersController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }


    /**
     * @param User $user
     * @return Application|Factory|View
     */
    public function show(User $user)
    {
        return view('client.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return Application|Factory|View
     */
    public function edit(User $user)
    {
        return view('client.users.edit', compact('user'));
    }


    /**
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $request->validate(['name' => ['required', 'string', 'max:255']]);
        $user->name = $request->get('name');
        $user->save();

        return redirect()->route('users.show', ['user' => $user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.users.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                           name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                           name="email" value="{{ old('email') }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror"
                                           name="password" required autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                           name="password_confirmation" required autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create User') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3><b>Edit User name</b></h3>

    <form class=" row g-3" method="POST" action="{{route('admin.users.update', ['user' => $user])}}">
        @csrf
        @method('PUT')
        <div class="col-md-6">
            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                           value="{{ $user->name }}" required autocomplete="name" autofocus>

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                         <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>

            <input type="hidden" name="user_id" value="{{$user->id}}">

            <div class="mb-5">
                <button type="submit" class="btn btn-secondary">Update Name</button>
                <a href=" {{ route('admin.users.index') }} " class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')

    <a href="{{route('admin.users.create')}}" class="btn btn-outline-success">Create User</a>
    <table class="table mt-3" style="padding-top: 30px">
        <thead class="thead-dark">
        <tr>
            <th scope="col">User Name</th>
            <th scope="col" class="text-center">Email</th>
            <th scope="col" class="text-center">Is Admin</th>
            <th scope="col" class="text-right">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>
                    <a href="{{route('admin.users.show', ['user' => $user])}}">{{$user->name}}</a>
                </td>
                <td class="text-center">
                    {{$user->email}}
                </td>

                <td class="text-center">
                    @if($user->is_admin)
                        Admin
                    @else
                        User
                    @endif
                </td>

                <td class="text-right">
                    <div class="btn-group">
                        <form class="my-3" action="{{ route('admin.users.destroy', ['user' => $user]) }}"
                              method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete User</button>
                            <a href="{{route('admin.users.edit', ['user' => $user])}}"
                               class="btn btn-outline-info btn-sm">Edit User</a>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <div class="row justify-content-md-center">
        <div class="col-md-auto">
            {{ $users->links('pagination::bootstrap-4') }}
        </div>
    </div>

@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="btn-group">
        <h3><b>{{$user->name}}, profile</b></h3>
        <a href="{{ route('admin.users.edit', ['user' => $user]) }}" class="btn btn-outline-info ml-4">Edit Name</a>
    </div>
    <div class="my-3">
        <h4>User Photos:</h4>
    </div>

    <table class="table mt-3" style="padding-top: 30px">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Image</th>
            <th scope="col" class="text-center">Name</th>
            <th scope="col" class="text-right">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($user->images as $image)
            <tr>
                <td>
                    <a href="{{route('admin.images.show', ['image' => $image])}}" class="text-decoration-none text-dark">
                        <img src="{{asset('/storage/' . $image->img)}}" alt="{{asset('/storage/' . $image->img)}}"
                             width="70px" height="70px">
                    </a>
                </td>
                <td class="text-center">
                    <a href="{{route('admin.images.show', ['image' => $image])}}" class="text-decoration-none text-dark">
                        {{$image->name}}
                    </a>
                </td>

                <td class="text-right">
                    <div class="btn-group">
                        <form class="my-3" action="{{ route('admin.images.destroy', ['image' => $image]) }}"
                              method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete Image</button>
                            <a href="{{route('admin.images.edit', ['image' => $image])}}"
                               class="btn btn-outline-info btn-sm">Edit Image</a>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>




    <div>
        <a href=" {{ route('admin.images.index') }} " class="btn btn-outline-secondary">Back</a>
    </div>
@endsection