routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Client\ImagesController::class, 'index'])
    ->name('images.index');

Route::resource('users', \App\Http\Controllers\Client\UsersController::class)
    ->only('show', 'edit', 'update')
    ->middleware('auth');

Route::resource('images', \App\Http\Controllers\Client\ImagesController::class)
    ->except('index', 'create', 'store');

Route::get('imagas/create', [\App\Http\Controllers\Client\ImagesController::class, 'create'])
    ->name('images.create')->middleware('auth');

Route::post('images', [\App\Http\Controllers\Client\ImagesController::class, 'store'])
    ->name('images.store')->middleware('auth');

Route::resource('comments', \App\Http\Controllers\Client\CommentsController::class)
    ->only('store', 'destroy')
    ->middleware('auth');


Route::prefix('admin')->middleware(['auth', 'admin'])->name('admin.')->group(function () {
    Route::resources([
        'images' => \App\Http\Controllers\Admin\ImagesController::class,
        'comments' => \App\Http\Controllers\Admin\CommentsController::class,
        'users' => \App\Http\Controllers\Admin\UsersController::class
    ]);
});

Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Gallery</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Photo Gallery
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link  " href="{{route('users.show', ['user' => Auth::user()])}}">My profile</a>
                            </li>
                            @if(Auth::user()->is_admin)
                                <li class="nav-item dropdown">
                                    <a id="admin" class="nav-link dropdown-toggle" href="#" role="button"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        Admin
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="admin">
                                        <a class="dropdown-item" href="{{ route('admin.images.index') }}">
                                            All Images
                                        </a>
                                        <a class="dropdown-item" href="{{ route('admin.users.index') }}">
                                            All Users
                                        </a>
                                        <a class="dropdown-item" href="{{ route('admin.comments.index') }}">
                                            All Comments
                                        </a>
                                    </div>
                                </li>
                            @endif
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @yield('content')
        </main>
    </div>
</body>
</html>